name: revisions
description: "Keep your users up to date with the latest changes in your app."
version: 0.0.1
homepage: "https://therevisions.app"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_markdown: ^0.6.18+2
  freezed_annotation: ^2.4.1
  http: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  markdown: ^7.1.1
  nanoid2: ^2.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ">=2.0.0 <5.0.0"
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter: